---
parent: 'common/test_cases/origin_installed_release.yml'
overrides:
  junit_analysis: True
  timer: 'H H * * *'
  email:
    - bparees@redhat.com
    - cewong@redhat.com
    - gmontero@redhat.com
    - cdaley@redhat.com
    - jminter@redhat.com
    - miminar@redhat.com
    - obulatov@redhat.com
    - agladkov@redhat.com
extensions:
  actions:
    - type: "script"
      title: "run extended tests"
      repository: "origin"
      script: |-
        test/extended/clusterup.sh
