---
parent: 'common/test_cases/origin.yml'
overrides:
  junit_analysis: False
extensions:
  actions:
    - type: "script"
      title: "run unit tests"
      repository: "cluster-operator"
      script: |-
        make test